// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, update_at, name, phone_number, email)
VALUES ($1, NOW(), NOW(), $2, $3, $4)
RETURNING id, created_at, update_at, name, phone_number, email
`

type CreateUserParams struct {
	ID          uuid.UUID
	Name        string
	PhoneNumber string
	Email       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.PhoneNumber,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdateAt,
		&i.Name,
		&i.PhoneNumber,
		&i.Email,
	)
	return i, err
}
