// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events(id, created_at, updated_at, name, owner_id, type, occurs_on, expires_at)
VALUES (gen_random_uuid(), NOW(), NOW(), $1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, name, owner_id, type, occurs_on, expires_at
`

type CreateEventParams struct {
	Name      string
	OwnerID   uuid.UUID
	Type      string
	OccursOn  time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Name,
		arg.OwnerID,
		arg.Type,
		arg.OccursOn,
		arg.ExpiresAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OwnerID,
		&i.Type,
		&i.OccursOn,
		&i.ExpiresAt,
	)
	return i, err
}
