// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addEventResponder = `-- name: AddEventResponder :one
UPDATE events
SET respondants = array_append(respondants, $1),
updated_at = NOW()
WHERE id = $2
RETURNING id, created_at, updated_at, name, owner_id, occurs_on, expires_at, min_volunteers, max_volunteers, respondants, description, category
`

type AddEventResponderParams struct {
	ArrayAppend interface{}
	ID          uuid.UUID
}

func (q *Queries) AddEventResponder(ctx context.Context, arg AddEventResponderParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, addEventResponder, arg.ArrayAppend, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OwnerID,
		&i.OccursOn,
		&i.ExpiresAt,
		&i.MinVolunteers,
		&i.MaxVolunteers,
		pq.Array(&i.Respondants),
		&i.Description,
		&i.Category,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
WITH inserted as (INSERT INTO events(
    id, 
    created_at, updated_at, 
    name, 
    description,
    owner_id, 
    category, 
    occurs_on, expires_at,
    min_volunteers, max_volunteers)
VALUES (gen_random_uuid(), NOW(), NOW(), 
    $1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, created_at, updated_at, name, owner_id, occurs_on, expires_at, min_volunteers, max_volunteers, respondants, description, category)
SELECT inserted.id, inserted.created_at, inserted.updated_at, inserted.name, inserted.owner_id, inserted.occurs_on, inserted.expires_at, inserted.min_volunteers, inserted.max_volunteers, inserted.respondants, inserted.description, inserted.category, u.name as creator_name
FROM inserted
JOIN users u ON u.id = inserted.owner_id
`

type CreateEventParams struct {
	Name          string
	Description   string
	OwnerID       uuid.UUID
	Category      Genre
	OccursOn      time.Time
	ExpiresAt     time.Time
	MinVolunteers sql.NullInt32
	MaxVolunteers sql.NullInt32
}

type CreateEventRow struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	OwnerID       uuid.UUID
	OccursOn      time.Time
	ExpiresAt     time.Time
	MinVolunteers sql.NullInt32
	MaxVolunteers sql.NullInt32
	Respondants   []uuid.UUID
	Description   string
	Category      Genre
	CreatorName   string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.Category,
		arg.OccursOn,
		arg.ExpiresAt,
		arg.MinVolunteers,
		arg.MaxVolunteers,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OwnerID,
		&i.OccursOn,
		&i.ExpiresAt,
		&i.MinVolunteers,
		&i.MaxVolunteers,
		pq.Array(&i.Respondants),
		&i.Description,
		&i.Category,
		&i.CreatorName,
	)
	return i, err
}

const getEventRespondants = `-- name: GetEventRespondants :many
SELECT u.id, u.name, u.phone_number, u.email
FROM users u
JOIN events e ON u.id = ANY(e.respondants)
WHERE e.id = $1
`

type GetEventRespondantsRow struct {
	ID          uuid.UUID
	Name        string
	PhoneNumber string
	Email       string
}

func (q *Queries) GetEventRespondants(ctx context.Context, id uuid.UUID) ([]GetEventRespondantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventRespondants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventRespondantsRow
	for rows.Next() {
		var i GetEventRespondantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhoneNumber,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByCategory = `-- name: GetEventsByCategory :many
SELECT id, created_at, updated_at, name, owner_id, occurs_on, expires_at, min_volunteers, max_volunteers, respondants, description, category FROM events
WHERE category = ANY($1::GENRE[])
`

func (q *Queries) GetEventsByCategory(ctx context.Context, dollar_1 []Genre) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByCategory, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.OwnerID,
			&i.OccursOn,
			&i.ExpiresAt,
			&i.MinVolunteers,
			&i.MaxVolunteers,
			pq.Array(&i.Respondants),
			&i.Description,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByOwner = `-- name: GetEventsByOwner :many
SELECT id, created_at, updated_at, name, owner_id, occurs_on, expires_at, min_volunteers, max_volunteers, respondants, description, category FROM events
WHERE owner_id = $1
`

func (q *Queries) GetEventsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.OwnerID,
			&i.OccursOn,
			&i.ExpiresAt,
			&i.MinVolunteers,
			&i.MaxVolunteers,
			pq.Array(&i.Respondants),
			&i.Description,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEventResponder = `-- name: RemoveEventResponder :one
UPDATE events
SET respondants = array_remove(respondants, $1),
updated_at = NOW()
WHERE id = $2
RETURNING id, created_at, updated_at, name, owner_id, occurs_on, expires_at, min_volunteers, max_volunteers, respondants, description, category
`

type RemoveEventResponderParams struct {
	ArrayRemove interface{}
	ID          uuid.UUID
}

func (q *Queries) RemoveEventResponder(ctx context.Context, arg RemoveEventResponderParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, removeEventResponder, arg.ArrayRemove, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OwnerID,
		&i.OccursOn,
		&i.ExpiresAt,
		&i.MinVolunteers,
		&i.MaxVolunteers,
		pq.Array(&i.Respondants),
		&i.Description,
		&i.Category,
	)
	return i, err
}

const updateEventByID = `-- name: UpdateEventByID :one
UPDATE events
SET updated_at = NOW(), name = $1,
description = $2, category = $3, occurs_on = $4,
expires_at = $5, min_volunteers = $6, max_volunteers = $7
WHERE id = $8
RETURNING id, created_at, updated_at, name, owner_id, occurs_on, expires_at, min_volunteers, max_volunteers, respondants, description, category
`

type UpdateEventByIDParams struct {
	Name          string
	Description   string
	Category      Genre
	OccursOn      time.Time
	ExpiresAt     time.Time
	MinVolunteers sql.NullInt32
	MaxVolunteers sql.NullInt32
	ID            uuid.UUID
}

func (q *Queries) UpdateEventByID(ctx context.Context, arg UpdateEventByIDParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEventByID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.OccursOn,
		arg.ExpiresAt,
		arg.MinVolunteers,
		arg.MaxVolunteers,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OwnerID,
		&i.OccursOn,
		&i.ExpiresAt,
		&i.MinVolunteers,
		&i.MaxVolunteers,
		pq.Array(&i.Respondants),
		&i.Description,
		&i.Category,
	)
	return i, err
}
