// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outgoing.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOutgoing = `-- name: CreateOutgoing :one
INSERT INTO outgoingmessages(id, created_at, updated_at, encoded_msg, sent)
VALUES (gen_random_uuid(), NOW(), NOW(), $1, false)
RETURNING id, created_at, updated_at, encoded_msg, sent
`

func (q *Queries) CreateOutgoing(ctx context.Context, encodedMsg []byte) (Outgoingmessage, error) {
	row := q.db.QueryRowContext(ctx, createOutgoing, encodedMsg)
	var i Outgoingmessage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EncodedMsg,
		&i.Sent,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, created_at, updated_at, encoded_msg, sent FROM outgoingmessages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Outgoingmessage, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i Outgoingmessage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EncodedMsg,
		&i.Sent,
	)
	return i, err
}

const updateByIDtoSENT = `-- name: UpdateByIDtoSENT :exec
UPDATE outgoingmessages
SET updated_at=NOW(), sent=true
where id = $1
`

func (q *Queries) UpdateByIDtoSENT(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateByIDtoSENT, id)
	return err
}
