// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refreshtokens(token, created_at, updated_at, user_id, expires_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    date_add(NOW(), '60 days')
) returning token, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	Token  string
	UserID uuid.UUID
}

type CreateRefreshTokenRow struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.Token, arg.UserID)
	var i CreateRefreshTokenRow
	err := row.Scan(&i.Token, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at FROM refreshtokens
WHERE token = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (Refreshtoken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i Refreshtoken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserfromRefreshToken = `-- name: GetUserfromRefreshToken :one
SELECT refreshtokens.token, refreshtokens.created_at, refreshtokens.updated_at, refreshtokens.user_id, refreshtokens.expires_at, refreshtokens.revoked_at, refreshtokens.token, refreshtokens.created_at, refreshtokens.updated_at, refreshtokens.user_id, refreshtokens.expires_at, refreshtokens.revoked_at FROM refreshtokens
JOIN refreshtokens on users.id = refreshtokens.user_id
WHERE refreshtokens.token = $1
AND revoked_at IS NULL
AND expires_at > NOW()
`

type GetUserfromRefreshTokenRow struct {
	Token       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
	ExpiresAt   time.Time
	RevokedAt   sql.NullTime
	Token_2     string
	CreatedAt_2 time.Time
	UpdatedAt_2 time.Time
	UserID_2    uuid.UUID
	ExpiresAt_2 time.Time
	RevokedAt_2 sql.NullTime
}

func (q *Queries) GetUserfromRefreshToken(ctx context.Context, token string) (GetUserfromRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserfromRefreshToken, token)
	var i GetUserfromRefreshTokenRow
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Token_2,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.UserID_2,
		&i.ExpiresAt_2,
		&i.RevokedAt_2,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE refreshtokens
SET updated_at = NOW(), revoked_at = NOW()
WHERE token = $1
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}
