// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const clearUsers = `-- name: ClearUsers :exec
DELETE FROM users
`

func (q *Queries) ClearUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearUsers)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, name, phone_number, email, hashed_password)
VALUES (gen_random_uuid(), NOW(), NOW(), $1, $2, $3, $4)
RETURNING id, created_at, updated_at, name, phone_number, email, hashed_password, subs
`

type CreateUserParams struct {
	Name           string
	PhoneNumber    string
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.PhoneNumber,
		arg.Email,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		pq.Array(&i.Subs),
	)
	return i, err
}

const getUserByNameEmail = `-- name: GetUserByNameEmail :one
SELECT id, created_at, updated_at, name, phone_number, email
FROM users
WHERE name = $1 and email = $2
`

type GetUserByNameEmailParams struct {
	Name  string
	Email string
}

type GetUserByNameEmailRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	PhoneNumber string
	Email       string
}

func (q *Queries) GetUserByNameEmail(ctx context.Context, arg GetUserByNameEmailParams) (GetUserByNameEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByNameEmail, arg.Name, arg.Email)
	var i GetUserByNameEmailRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.PhoneNumber,
		&i.Email,
	)
	return i, err
}

const getUserNameOnly = `-- name: GetUserNameOnly :one
SELECT name FROM users
WHERE id = $1
`

func (q *Queries) GetUserNameOnly(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserNameOnly, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUserforLogin = `-- name: GetUserforLogin :one
SELECT id, created_at, updated_at, name, phone_number, email, hashed_password, subs FROM users
WHERE name = $1 and email = $2
`

type GetUserforLoginParams struct {
	Name  string
	Email string
}

func (q *Queries) GetUserforLogin(ctx context.Context, arg GetUserforLoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserforLogin, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.PhoneNumber,
		&i.Email,
		&i.HashedPassword,
		pq.Array(&i.Subs),
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, created_at, updated_at, name, phone_number, email, hashed_password, subs
FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.PhoneNumber,
			&i.Email,
			&i.HashedPassword,
			pq.Array(&i.Subs),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
